version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - database.env # configure postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    user:
    	1000:1000
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge


